### ISSUE TITLE
Fix errornous tweet replies short.co ######## #UXD #Bug

### ISSUE THREAD

**Issue by ldexterldesign** [kiriappeee/reply-later#43]
Hey,

Thanks again for application

There seems to be a bug which spits out an errornous reply to scheduled tweets ( i.e. https://twitter.com/ldexterldesign/status/692247394881269760 ):

<blockquote class="twitter-tweet" lang="en"><p lang="und" dir="ltr"><a href="https://twitter.com/ldexterldesign">@ldexterldesign</a> <a href="https://t.co/BNRGEGEakd">https://t.co/BNRGEGEakd</a>########</p>&mdash; Lewis Litanzios (@ldexterldesign) <a href="https://twitter.com/ldexterldesign/status/692247397116809216">January 27, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<img width="1440" alt="screen shot 2016-01-27 at 11 01 53" src="https://cloud.githubusercontent.com/assets/1715809/12609976/690df5f2-c4e5-11e5-8f5c-329647469142.png">

Hope this is useful and to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
Hmm, I see it's happened again, but this time I think I can make sense of it...

<blockquote class="twitter-tweet" lang="en"><p lang="und" dir="ltr"><a href="https://twitter.com/ldexterldesign">@ldexterldesign</a> <a href="https://twitter.com/hashtag/Quote?src=hash">#Quote</a></p>&mdash; Lewis Litanzios (@ldexterldesign) <a href="https://twitter.com/ldexterldesign/status/692322891367485441">January 27, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<img width="1440" alt="screen shot 2016-01-27 at 14 21 29" src="https://cloud.githubusercontent.com/assets/1715809/12614608/4bdf68e6-c501-11e5-88fa-049582faf27f.png">

By viewing my "Sent" schedule ( http://replylater.adnanissadeen.com/replylater/app/viewschedule/?view=sent ) I can see "#Quote" is the final word of this scheduled tweet:

<img width="669" alt="screen shot 2016-01-27 at 14 22 37" src="https://cloud.githubusercontent.com/assets/1715809/12614637/800f241c-c501-11e5-878c-16f2d0962f54.png">

Is it expected behaviour that your app' will chain tweets >140 characters as replies? If so, that could be an interesting feature ~ http://tweetstorm.io/

Hope to hear back

Thanks

**Comment by kiriappeee** [comment]
hey @ldexterldesign you are absolutely spot on in saying that the tool will auto chain tweets > 140 characters as replies in the correct tweet stormed order. The short.co url is an actual issue. Looking into it :)

**Comment by ldexterldesign** [comment]
Great, if it's not already documented I'd suggest you do so; since I wasn't aware of this feature and discovered by accident

Good luck with the fix!

Kind thanks

PS Are you looking for [front-end/UXD] help with this project, as I'd love to be involved?

**Comment by ldexterldesign** [comment]
https://twitter.com/kiriappeee/status/699978214886678528

Hey,

Hope you're well

I still find the app' really useful and would use it more if this issue got resolved - disconcerting to find tweets like this in one's stream the next day https://twitter.com/ldexterldesign/status/727866063954661376 😔

Hope to hear back

Kind thanks

**Comment by kiriappeee** [comment]
@ldexterldesign I'll be looking into this tomorrow morning. I'm also starting work on a feature to schedule tweet storms (think that might interest you :) )

**Comment by ldexterldesign** [comment]
How did you get on?

Still buggy https://twitter.com/ldexterldesign/status/732824666381914112

Hope this is useful and to hear back

Kind thanks

**Comment by ldexterldesign** [comment]
Hey,

Your app's become unusable ~ https://twitter.com/search?f=tweets&q=ldexterldesign%20short.co

It's with regret that, today, I removed your pinned browser tab

Let me know if you decide to fix things up

In the meantime I'll look for a replacement tool

Regards
